### PR TITLE
Support for DayZ 1.8, camo nets, various traps and dometents

### PR DESCRIPTION
**Pull request by wterpstra**
Added support for camo nets, various craftable traps and dometents used in the DayZ 1.8 update.

Both stashes (medium & small) now use the same stash.png icon.

### CODE REVIEW

**Comment by Skaronator** [comment]
BearTrap_DZ is missing ;)

**Comment by wterpstra** [comment]
Ah, I see, will add it! Thanks!

**Comment by wterpstra** [comment]
Added!

**Comment by wterpstra** [comment]
If I look at the deployable table in the Reality database:
Id: 2
class_name: TrapBear

Or is that a bug with reality and should that classname be changed too?

**Comment by Skaronator** [comment]
Visad forgot to change it I'll say it him later in Skype ;)
New Classname is BearTrap_DZ, i'm 100% sure
Img
Line 133 at dayz_code/Configs/CfgMagazines/Deployable.hpp
Maybe few lines up/down because this is the 1.8.0.1 Developer File ;)

**Comment by wterpstra** [comment]
Okay, i'll add it to the pull request that is still open.

Great work on DayZ mod!

**Pull request merged**
