### PR TITLE
Fixed kill counters in player tooltip, hiding of tooltips with icons, fix for beartrap, added beartrap icon

### PR DESCRIPTION
**Pull request by wterpstra**
Fixed kill counters in player tooltip.

Changed TrapBear to BearTrap_DZ classname.

Added beartrap icon

Fixed an issue with tooltips not hiding when hiding icons.

### CODE REVIEW

**Comment by Skaronator** [comment]
Please visit: https://github.com/wterpstra/DayZMapper/commit/0c34d72a0eba2b573970476a1432cbf1c3869ca0#commitcomment-4154247

**Comment by wterpstra** [comment]
Renaming TrapBear to BearTrap_DZ, will reopen when changes are comitted

**Comment by Skaronator** [comment]
btw: here are all obj. which are deployable
SafeObjects = ["Land_Fire_DZ", "TentStorage", "Wire_cat1", "Sandbag1_DZ", "Hedgehog_DZ", "StashSmall", "StashMedium", "BearTrap_DZ", "DomeTentStorage", "CamoNet_DZ", "Trap_Cans", "TrapTripwireFlare", "TrapBearTrapSmoke", "TrapTripwireGrenade", "TrapTripwireSmoke", "TrapBearTrapFlare"];

DomeTentStorage > will be added in 1.8.0.1

**Comment by wterpstra** [comment]
Thanks, will add the Land_Fire_DZ as well!

**Comment by Skaronator** [comment]
Oh right, we has change the Land_Fire name, forgot is already^

**Comment by Skaronator** [comment]
But Land Fire isnt synced to the db

**Comment by wterpstra** [comment]
Oh okay, will this be done in the future? Because i just made this sweet campfire icon: fire

**Comment by Skaronator** [comment]
lol but i think not because the world could be spamed with a big Fire :P

**Comment by wterpstra** [comment]
I'll leave the Land_Fire out then, should be working now!

**Comment by wterpstra** [comment]
Fixed an issue when hiding icons that the tooltips still show when hovering on the invisible icon. Also added a beartrap icon. beartrap

**Pull request merged**
