### PR TITLE
Example for Noobs

### PR DESCRIPTION
**Pull request by Skaronator**

### CODE REVIEW

**Comment by zamp** [comment]
Nobody is born as a smith.

**Comment by OllieB** [comment]
Just FYI localhost != 127.0.0.1 when connecting to mySQL instances. localhost is much more efficient (uses system socket)

**Comment by zamp** [comment]
DayZ database only accepts TCP connections.

**Comment by OllieB** [comment]
Not if your MySQL instance is correctly configured...

**Comment by zamp** [comment]
Yeah looks like they changed it. Didn't use to work with system socket.

**Pull request closed without merging**
